name: Tests

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ls
        run: ls -al

      - name: sha
        run: echo ${{ github.sha }}

      - name: cat
        run: cat README.md
